# Generated by Django 4.2.19 on 2025-03-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
